export const MAIN = "/"
export const ABOUT_ME = "/about-me"
export const INSTAGRAMCLONE = "/projects/instagram-clone"
export const OPTICAVZOR = "/projects/optica-vzor"
export const TENNISCENTER = "/projects/tennis-center"